**Supervised machine learning** means training a model using labeled data, where you have:
- Input (features/X): the information the model uses to make a prediction.
- Expected target (label/y): the correct answer you want the model to learn.

### glob
Go into this folder and find all files that match this pattern

When many files have a predictable naming pattern, glob saves you from manually writing every file path by using a wildcard (*) to find all matching files automatically.

Hard-coding a list of filenames creates brittle code — the moment a filename changes or a sixth year of data is added, your script breaks silently or requires manual editing. glob is the robust alternative: it finds whatever files match the pattern at runtime, making the pipeline self-updating as new data arrives.

In [6]:
import pandas as pd
import numpy as np
from glob import glob

In [8]:
datasets=glob("../data/buenos-aires-real-estate-*.csv")
datasets

['../data/buenos-aires-real-estate-3.csv',
 '../data/buenos-aires-real-estate-2.csv',
 '../data/buenos-aires-real-estate-1.csv',
 '../data/buenos-aires-real-estate-5.csv',
 '../data/buenos-aires-real-estate-4.csv']

In [12]:
files=[]
for dataset in datasets:
    data=pd.read_csv(dataset)
    files.append(data)
len(files)

5

In [13]:
df=pd.concat(files,ignore_index=True)

In [15]:
df.head()

,operation,property_type,place_with_parent_names,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url
0,sell,house,|Argentina|Bs.As. G.B.A. Zona Oeste|Moreno|Mor...,NaN,180000.0,USD,2729232.0,180000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://moreno.properati.com.ar/10rhr_venta_cas...
1,sell,house,|Argentina|Bs.As. G.B.A. Zona Oeste|Morón|,"-34.6624160375,-58.6044728878",125000.0,USD,1895300.0,125000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://moron-bs-as-g-b-a-zona-oeste.properati....
2,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Sur|Lanús|Lanús|,"-34.7033677191,-58.3923923872",175000.0,USD,2653420.0,175000.0,100.0,92.0,1750.0,1902.173913,NaN,4.0,2.0,http://lanus.properati.com.ar/pzqo_venta_depar...
3,sell,PH,|Argentina|Bs.As. G.B.A. Zona Oeste|La Matanza...,NaN,NaN,NaN,NaN,NaN,199.0,110.0,NaN,NaN,NaN,3.0,NaN,http://ramos-mejia.properati.com.ar/sat2_venta...
4,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Oeste|Ituzaingó|...,NaN,90000.0,USD,1364616.0,90000.0,NaN,70.0,NaN,1285.714286,NaN,3.0,NaN,http://ituzaingo.properati.com.ar/smi9_venta_d...

In [16]:
def merge_files(data):
    return pd.concat([pd.read_csv(file) for file in glob(data)],ignore_index=True)

In [17]:
merge_files("../data/buenos-aires-real-estate-*.csv").info()

<class 'pandas.DataFrame'>
RangeIndex: 43029 entries, 0 to 43028
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   operation                   43029 non-null  str
 1   property_type               43029 non-null  str
 2   place_with_parent_names     43029 non-null  str
 3   lat-lon                     34734 non-null  str
 4   price                       38073 non-null  float64
 5   currency                    38072 non-null  str
 6   price_aprox_local_currency  38073 non-null  float64
 7   price_aprox_usd             38073 non-null  float64
 8   surface_total_in_m2         29871 non-null  float64
 9   surface_covered_in_m2       36420 non-null  float64
 10  price_usd_per_m2            24449 non-null  float64
 11  price_per_m2                32642 non-null  float64
 12  floor                       6505 non-null   float64
 13  rooms                       23806 non-null  float64
 14  expenses                    4452 non-null   float64
 15  properati_url               43029 non-null  str
dtypes: float64(10), str(6)
memory usage: 5.3 MB

## Data Cleaning

In [18]:
df.head()

,operation,property_type,place_with_parent_names,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url
0,sell,house,|Argentina|Bs.As. G.B.A. Zona Oeste|Moreno|Mor...,NaN,180000.0,USD,2729232.0,180000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://moreno.properati.com.ar/10rhr_venta_cas...
1,sell,house,|Argentina|Bs.As. G.B.A. Zona Oeste|Morón|,"-34.6624160375,-58.6044728878",125000.0,USD,1895300.0,125000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://moron-bs-as-g-b-a-zona-oeste.properati....
2,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Sur|Lanús|Lanús|,"-34.7033677191,-58.3923923872",175000.0,USD,2653420.0,175000.0,100.0,92.0,1750.0,1902.173913,NaN,4.0,2.0,http://lanus.properati.com.ar/pzqo_venta_depar...
3,sell,PH,|Argentina|Bs.As. G.B.A. Zona Oeste|La Matanza...,NaN,NaN,NaN,NaN,NaN,199.0,110.0,NaN,NaN,NaN,3.0,NaN,http://ramos-mejia.properati.com.ar/sat2_venta...
4,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Oeste|Ituzaingó|...,NaN,90000.0,USD,1364616.0,90000.0,NaN,70.0,NaN,1285.714286,NaN,3.0,NaN,http://ituzaingo.properati.com.ar/smi9_venta_d...

In [19]:
df.shape

(43029, 16)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43029 entries, 0 to 43028
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   operation                   43029 non-null  str
 1   property_type               43029 non-null  str
 2   place_with_parent_names     43029 non-null  str
 3   lat-lon                     34734 non-null  str
 4   price                       38073 non-null  float64
 5   currency                    38072 non-null  str
 6   price_aprox_local_currency  38073 non-null  float64
 7   price_aprox_usd             38073 non-null  float64
 8   surface_total_in_m2         29871 non-null  float64
 9   surface_covered_in_m2       36420 non-null  float64
 10  price_usd_per_m2            24449 non-null  float64
 11  price_per_m2                32642 non-null  float64
 12  floor                       6505 non-null   float64
 13  rooms                       23806 non-null  float64
 14  expenses                    4452 non-null   float64
 15  properati_url               43029 non-null  str
dtypes: float64(10), str(6)
memory usage: 5.3 MB

In [21]:
df.dtypes

operation                         str
property_type                     str
place_with_parent_names           str
lat-lon                           str
price                         float64
currency                          str
price_aprox_local_currency    float64
price_aprox_usd               float64
surface_total_in_m2           float64
surface_covered_in_m2         float64
price_usd_per_m2              float64
price_per_m2                  float64
floor                         float64
rooms                         float64
expenses                      float64
properati_url                     str
dtype: object

In [23]:
df.isnull().sum()

operation                         0
property_type                     0
place_with_parent_names           0
lat-lon                        8295
price                          4956
currency                       4957
price_aprox_local_currency     4956
price_aprox_usd                4956
surface_total_in_m2           13158
surface_covered_in_m2          6609
price_usd_per_m2              18580
price_per_m2                  10387
floor                         36524
rooms                         19223
expenses                      38577
properati_url                     0
dtype: int64

In [26]:
df.loc[lambda x:x["property_type"]=="apartment"]

,operation,property_type,place_with_parent_names,lat-lon,price,currency,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,properati_url
2,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Sur|Lanús|Lanús|,"-34.7033677191,-58.3923923872",175000.0,USD,2653420.00,175000.00,100.0,92.0,1750.000000,1902.173913,NaN,4.0,2.0,http://lanus.properati.com.ar/pzqo_venta_depar...
4,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Oeste|Ituzaingó|...,NaN,90000.0,USD,1364616.00,90000.00,NaN,70.0,NaN,1285.714286,NaN,3.0,NaN,http://ituzaingo.properati.com.ar/smi9_venta_d...
6,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Oeste|Moreno|,"-34.6501996137,-58.7923693657",85000.0,USD,1288804.00,85000.00,68.0,68.0,1250.000000,1250.000000,NaN,NaN,NaN,http://moreno-bs-as-g-b-a-zona-oeste.properati...
7,sell,apartment,|Argentina|Capital Federal|Villa General Mitre|,"-34.616004,-58.470506",120000.0,USD,1819488.00,120000.00,NaN,55.0,NaN,2181.818182,NaN,2.0,NaN,http://villa-general-mitre.properati.com.ar/xx...
8,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Norte|General Sa...,"-34.5525858,-58.560368",NaN,NaN,NaN,NaN,57.0,50.0,NaN,NaN,1.0,2.0,NaN,http://villa-ballester.properati.com.ar/yolx_v...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43023,sell,apartment,|Argentina|Capital Federal|San Telmo|,"-34.6233348,-58.3748384",85267.0,USD,1292852.36,85267.00,40.0,38.0,2131.675000,2243.868421,NaN,1.0,NaN,http://san-telmo.properati.com.ar/vayv_venta_d...
43024,sell,apartment,|Argentina|Capital Federal|Barracas|,"-34.631213,-58.371545",1200000.0,ARS,1196669.37,78923.48,NaN,50.0,NaN,24000.000000,NaN,2.0,NaN,http://barracas.properati.com.ar/11bzh_venta_d...
43025,sell,apartment,|Argentina|Capital Federal|Palermo|,"-34.5625,-58.458333",240000.0,USD,3638976.00,240000.00,55.0,44.0,4363.636364,5454.545455,NaN,2.0,NaN,http://palermo.properati.com.ar/ounv_venta_dep...
43026,sell,apartment,|Argentina|Capital Federal|Villa Luro|,"-34.6444745,-58.4959441",844779.0,ARS,842434.31,55560.75,0.0,38.0,NaN,22231.026320,NaN,1.0,NaN,http://villa-luro.properati.com.ar/sj8e_venta_...
43028,sell,apartment,|Argentina|Bs.As. G.B.A. Zona Oeste|Morón|,"-34.656711555,-58.6213565927",68000.0,USD,1031043.20,68000.00,41.0,38.0,1658.536585,1789.473684,NaN,NaN,NaN,http://moron-bs-as-g-b-a-zona-oeste.properati....

In [ ]:
df.de